apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighttpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighttpd
  template:
    metadata:
      labels:
        app: lighttpd
    spec:
      containers:
      - name: lighttpd
        image: mikkyg/mk-lighttpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lighttpd
spec:
  selector:
    app: lighttpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
