apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: mikkyg/mk-nodejs
        env:
        - name: DB_HOST
          value: mariadb
        - name: DB_USER
          value: db_user
        - name: DB_PASSWORD
          value: db_password
        - name: DB_DATABASE
          value: mydatabase
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
